added template options for size / scalability
adamchainz/treepoem pull request #432
Opened 2022-10-25 17:39 UTC by nicohein

Hi @adamchainz,

I added some template options in line with this documentation: [Resizing-Symbols](https://github.com/bwipp/postscriptbarcode/wiki/Resizing-Symbols) and adjusted the PyTest `test_barcode` to cover resizing a barcode. 

I would appreciate if you would consider to incorporate this feature. Happy to receive feedback regarding the implementation.

2022-11-11 10:10 UTC, adamchainz requested changes
Thank you for the PR. This seems like a good addition.

I’ve left some comments below.

I would make some adjustments to your PR but you made it from your `main` branch, which prevents me from pushing to it on GitHub. Please always make open source PR’s from a feature branch.

Also, whenever you open an open source PR, plaese change the documentation and add a changelog note as well. Otherwise you’re proposing a “secret feature” for yourself, or you’re forcing the maintainer to do that work.

2022-11-11 10:10 UTC, adamchainz commented on src/treepoem/__init__.py
> +    template_options: dict[str, str] | None = None,
I don’t like adding "dictionary of arbitrary values" to the API, when in practice there’s a known set of options. Better to take the arguments exactly.

Also, I’m not convinced there’s really a use case for different scale values, as stretching dimensions different will break barcodes. Perhaps we should have one argument: `scale: int = 2` ?

2022-11-15 00:27 UTC, nicohein commented
Hi @adamchainz ,
I appreciate that you consider to incorporate this feature. I see your points and would probably ask for very similar changes if I was the maintainer. Please expect an update to this PR from my side in the coming days.
Best
Nico

2022-11-19 17:06 UTC, nicohein commented
Closing this PR in favour of https://github.com/adamchainz/treepoem/pull/437

2022-11-19 17:06 UTC, closed without merging